
SET SERVEROUTPUT ON

--EXCEPTIONS

--COLLECTION_IS_NULL    : ORA-06531 -> TENTATIVA DE APLICAR MÉTODOS QUE NAO O EXISTS PARA UMA COLLECTION NAO INICIALIZADA
--CURSOR_ALREADY_OPEN   : ORA-06511 -> TENTATIVA DE ABRIR UM CURSOR QUE JÁ ESTA ABERTO
--DUP_VAL_ON_INDEX      : ORA-00001 -> TENTATIVA DE INSERIR UM VALOR DUPLICADO EM UM INDICE UNICO
--INVALID_CURSOR        : ORA-01001 -> OCORREU UMA OPERAÇÃO ILEGAL EM UM CURSOR
--INVALID_NUMBER        : ORA-01722 -> FALHA NA CONVERSAO DE UMA STRING CARACTERE PARA NUMERICA
--LOGIN_DENIED          : ORA-01017 -> CONEXAO AO ORACLE COM UM NOME E/OU SENHA INVALIDA
--NO_DATA_FOUND         : ORA-01403 -> SELECT DO TIPO SINGLE-ROW NAO RETORNOU NENHUMA LINHA
--NOT_LOGGED_ON         : ORA-01012 -> PROGRAMA PLSQL EXECUTOU UMA CHAMADA AO BANCO DE DADOS SEM ESTAR CONECTADO AO ORACLE
--TIMEOUT_ON_RESOURCE   : ORA-00051 -> OCORREU UM TIME-OUT ENQUANTO O ORACLE ESTAVA AGUARDANDO POR UM RECURSO
--TOO_MANY_ROWS         : ORA-01422 -> SELECT DO TIPO SINGLE-ROW RETORNOU MAIS DE UMA LINHA
--VALUE_ERROR           : ORA-06502 -> OCORREU UM ERRO DE ARITMETICA, CONVERSAO OU TRUNCAMENTO
--ZERO_DIVIDE           : ORA-01476 -> TENTATIVA DE DIVISAO POR ZERO


DECLARE
    vRecord         employees.salary%TYPE;
BEGIN
    SELECT salary
    INTO vRecord
    FROM employees;
EXCEPTION
    WHEN TOO_MANY_ROWS
    THEN
        DBMS_OUTPUT.PUT_LINE('OCORREU UMA EXCEPTION DO TIPO TOO_MANY_ROWS');
END;


DECLARE
    vRecord         employees.salary%TYPE;
    vEmployee_id    employees.employee_id%TYPE := &vEmployee_id;
BEGIN
    SELECT salary
    INTO vRecord
    FROM employees
    WHERE employee_id = vEmployee_id;
    
    DBMS_OUTPUT.PUT_LINE('SALARIO: '|| vRecord);
EXCEPTION
    WHEN TOO_MANY_ROWS
    THEN
        RAISE_APPLICATION_ERROR(-20001, 'ERRO ORACLE: MUITAS LINHAS RETORNADAS EM UMA CONSULTA SINGLE ROW');
    WHEN OTHERS
    THEN
        RAISE_APPLICATION_ERROR(-20002, 'ERRO ORACLE: ' || SQLCODE || SQLERRM);
END;
