

CREATE OR REPLACE TRIGGER trigger_before_insert_employees
BEFORE INSERT OR UPDATE OR DELETE
ON employees
BEGIN
    IF (TO_CHAR(SYSDATE, 'DAY') IN ('SABADO', 'DOMINGO') OR TO_NUMBER(TO_CHAR(SYSDATE, 'HH24')) NOT BETWEEN 8 AND 15) THEN
    
        IF (INSERTING) THEN
            RAISE_APPLICATION_ERROR(-20001, 'O CADASTRO DE USUÁRIOS SÓ PODE SER REALIZADO DENTRO DO HORÁRIO COMERCIAL');
            ELSE IF (UPDATING) THEN
                RAISE_APPLICATION_ERROR(-20002, 'A ATUALIZAÇÃO DE USUÁRIOS SÓ PODE SER REALIZADO DENTRO DO HORÁRIO COMERCIAL');
            ELSE
                RAISE_APPLICATION_ERROR(-20003, 'A DELEÇÃO DE USUÁRIOS SÓ PODE SER REALIZADO DENTRO DO HORÁRIO COMERCIAL');
            END IF;
        END IF;
    END IF;
END;

DELETE
FROM employees
WHERE employee_id = 100;